name: InfiniteMITM
description: A MITM (man-in-the-middle) CLI for Halo Infinite
version: 0.5.6
author: Alexis Bize
repository: https://github.com/Alexis-Bize/InfiniteMITM
proxy:
  host: 127.0.0.1
  port: 1337
  certificate:
    name: InfiniteMITMRootCA
